name: Build and Release Application

on:
  push:
    tags:
      - v*.*.*

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Setup node v17
        uses: actions/setup-node@v1
        with:
          node-version: 17
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build application
        run: npm run package
      - name: Compress application
        run: cd out/STASYS-darwin-x64 && zip -r STASYS-macos.zip STASYS.app
      - name: Release application
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: out/STASYS-darwin-x64/STASYS-macos.zip

  build_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Setup node v17
        uses: actions/setup-node@v1
        with:
          node-version: 17
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Setup environment variables
        run: cd opencv-bindings && export OPENCV_ROOT=./prebuilt-opencv/ && cd ../
      - name: Build application
        run: npm run package
      - name: Compress application
        run: cd out/STASYS-win32-x64 && zip -r STASYS-windows.zip STASYS.app
      - name: Release application
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: out/STASYS-win32-x64/STASYS-windows.zip

