name: Build and Release Application

on:
  push:
    tags:
      - v*.*.*

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17
      - run: npm ci
      - run: npm run package
      - run: zip out/STASYS-macos.zip out/STASYS-darwin-x64
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: out/STASYS-macos.zip

